### ISSUE TITLE
sirius-pipeline : utils.cpp: In function ‘p4::config::v1::P4Info parse_p4info(const char*)’: google::protobuf::io issue

### ISSUE THREAD

**Issue by madhudhavala** [Azure/DASH#120]
Hello DASH community and @marian-pritsak 
Here i followed the steps mentioned in https://github.com/Azure/DASH/blob/main/sirius-pipeline/README.md
1) make clean  >>> working fine
2) make bmv2/sirius_pipeline.bmv2/sirius_pipeline.json >>> working fine
3) **make sai >>> not working well 
make sai has 2 steps one updating SAI folder and second compile created lib folder , seeing issue in compiling the lib fodler**

**Issue in detail:**
**A)** 
Updated SAI folder with teh steps mentioned in generate_dash_api.sh which is in SAI folder 
sudo ./SAI/sai_api_gen.py bmv2/sirius_pipeline.bmv2/sirius_pipeline_p4rt.json --ignore-tables=appliance,eni_meter,slb_decap --overwrite=true dash
**B)**
once SAI folder updated and correspodng lib folder created , the next step is 
cd lib
sudo make which results the following issue 
**$ sudo make**
g++ \
    -c \
    -I ../SAI/inc/ \
    -I ../SAI/experimental/ \
    -fPIC \
    -g \
    utils.cpp \
    saidash.cpp saidashacl.cpp saidashvnet.cpp 
utils.cpp: In function ‘p4::config::v1::P4Info parse_p4info(const char*)’:
**utils.cpp:62:27: error: ‘IstreamInputStream’ is not a member of ‘google::protobuf::io’; did you mean ‘CodedInputStream’?
   62 |     google::protobuf::io::IstreamInputStream istream_(&istream);
      |                           ^~~~~~~~~~~~~~~~~~
      |                           CodedInputStream
utils.cpp:63:42: error: ‘istream_’ was not declared in this scope; did you mean ‘istream’?
   63 |     google::protobuf::TextFormat::Parse(&istream_, &p4info);
      |                                          ^~~~~~~~
      |                                          istream
make: *** [Makefile:2: libsai.so] Error 1**

**ASK**
Need help on how to resolve this issue ? this is blokcing to move to next steps like
make test
make run-test

**Comment by chrispsommers** [comment]
Hi Madhu, I'm not sure why you experienced these errors, I've run the steps myself many times. You might have an environment issue. I can tell you I and my colleague are working on this particular area currently, including Github automation. I would respectfully ask that you hold off for a bit, get acquainted, and wait to see some forthcoming pull requests. Thank you!

**Comment by chrispsommers** [comment]
Hi @madhudhavala  are you still experiencing this in latest main branch? If not, please close. Thanks.

**Comment by chrispsommers** [comment]
Issue seems stale, closing.
