### ISSUE TITLE
IPv6 ACL support

### ISSUE THREAD

**Issue by KrisNey-MSFT** [Azure/DASH#122]
Needs to be coded in P4 behavioral model
No change in bmv2, just P4

Notes
Hi Mohammad, the following list of tables will require IPv6 support:
sirius_outbound.routing
sirius_outbound.ca_to_pa
ACL stages (sirius_acl file)
All those tables match on IPv4 address. We need to support matching on either IPv4 address or IPv6 address depending on the packet's overlay ethertype.
Per Mario Baldi - Collaborator
We will need IPv6 support also in connection tracking, hence generally throughout sirius_conntrack.p4.  My suggestion would be to first finalize connection tracking with the proper connection removal behavior just for IPv4 (building on the current version of the code) and then later add IPv6 support.

**Comment by KrisNey-MSFT** [comment]
@mhanif

**Comment by KrisNey-MSFT** [comment]
Also will need test cases

**Comment by mhanif** [comment]
Hi @KrisNey-MSFT, have provided (and passed) the test case but due to the [PTF thrift client issue](https://github.com/Azure/DASH/issues/237), haven't been able to run it in the existing PTF setup already checked in to the DASH repo.

**Comment by KrisNey-MSFT** [comment]
Per @mhanif - with the merge of [PR #222](https://github.com/Azure/DASH/pull/222), we should move the item 23 "IPv6 ACL Support" to "Done"

**Comment by chrispsommers** [comment]
We still need a tracking item for the test-cases, see https://github.com/Azure/DASH/issues/237

**Comment by KrisNey-MSFT** [comment]
@chrispsommers , is this for @KrisNey-MSFT or @mhanif to create?
TY!

**Comment by chrispsommers** [comment]
Hi @KrisNey-MSFT I guess the item would be "create the IPv6 vnet test case" which could be a "Project item" in either the BM or TestWG spreadsheet. Its status is "In progress," notes would be "Blocked by https://github.com/Azure/DASH/issues/237." Not sure which is the best place to track a test-case when it's being co-released with a feature in the P4 model. It seems like a BM project item.
