### ISSUE TITLE
Testing: Discuss test plan for pipeline (high level); Gerald, Marian, Chris

### ISSUE THREAD

**Issue by KrisNey-MSFT** [Azure/DASH#129]
All s/be common regardless of the framework

Discussed in the bmv2 WG; Chris asked for some initial VNET test cases
Nvidia to provide C code to program tables and send packets w/scapp1 (2 weeks) - Keysight will convert to an automated test

**Comment by chrispsommers** [comment]
The community has already begun to contribute vnet test-cases, this issue is stale now.
