### ISSUE TITLE
IPv6 IP Options extension headers

### ISSUE THREAD

**Issue by KrisNey-MSFT** [Azure/DASH#145]
In bmv2 we are currently not supporting (able to parse/process) extensions.  IPv6 has multiple headers.  In v4 and v6 we are handling only vanilla headers.  Supporting extension headers in bmv2.

**Comment by KrisNey-MSFT** [comment]
Saad has completed IPv4, would like to know how to test.  May also reach out to Chris if needed.

**Comment by KrisNey-MSFT** [comment]
hi @saad-mzhr - going through PRs, is there an update to this one?
@chrispsommers too

**Comment by chrispsommers** [comment]
> Saad has completed IPv4, would like to know how to test. May also reach out to Chris if needed.

Is there a PR for these enhancements? This seems like several months old so the P4 code will need to be synced to main. I recommend adding test cases to accompany the enhancements, using existing test cases as a starting point. In the PR, include a link to this issue so they will be cross-referenced. Thanks.

**Comment by saad-mzhr** [comment]
@KrisNey-MSFT 
These comments are old. I have already tested/discussed/approved and merged ipv4 related code into master. During discussion, it was told that these ipv4/ipv6 extensions were not actually needed at the moment. So I did not proceed with ipv6 part of this ticket.

**Comment by KrisNey-MSFT** [comment]
Thanks, is it ok if we close it out?  Os keep it open to remind us later of needed extensions? Let me know what you think… Thank you
________________________________

**Comment by KrisNey-MSFT** [comment]
Closing per comments above
