### ISSUE TITLE
Fix routing action in vnet-vnet document

### ISSUE THREAD

**Issue by mukeshmv** [Azure/DASH#148]
In this section of the doc
https://github.com/mmiele/DASH/blob/cb3d87ddf6247093c67f0ca6970c000d4db3857c/documentation/vnet2vnet-service/design/vnet-to-vnet-service.md#routing-a-packet-to-address-10101

```
1. Perform LPM lookup.
2. Select routing table DASH_ROUTE_TABLE:10.1.0.0/24. The action type is vnet and the value is Vnet1; and the overlay_ip=10.0.0.6.
3. Look up DASH_ROUTING_TYPE:vnet. The value for vnet is maprouting.
```
Points 2 and 3 above should have action type / routing type as vnet_direct instead of vnet.

**Comment by KrisNey-MSFT** [comment]
@mukeshmv fixed per your suggestion - please review

**Comment by KrisNey-MSFT** [comment]
fixed in 
https://github.com/Azure/DASH/pull/136/files?file-filters%5B%5D=.md&show-viewed-files=true#r921600385

**Comment by mukeshmv** [comment]
Tracked as PR comments
