### ISSUE TITLE
dash config json, why set 2 route objects instead of 1

### ISSUE THREAD

**Issue by mgheorghe** [Azure/DASH#169]
in https://github.com/Azure/DASH/blob/main/documentation/gnmi/design/dash-reference-config-example.md
we have
```
                "routes": [
                    {
                        "ip-prefixes": [ "10.1.0.0/16" ],
                        "action" : {
                            "routing-type": "vpc", // vnet route - destination within vnet, needs mapping table lookup
                            "vpc-id": "559c6ce8-26ab-4193-b946-ccc6e8f930b2"
                        },
                        "metering-bucket": 7 // default metering bucket that will be used in case mapping has metering bucket set to 0
                    },

                    {
                        "ip-prefixes": [ "10.1.0.128/28" ], // exempt subset of traffic from going thru firewall and allow to go directly
                        "action" : {
                            "routing-type": "vpc", // vnet route - destination within vnet, needs mapping table lookup
                            "vpc-id": "559c6ce8-26ab-4193-b946-ccc6e8f930b2"
                        },
                        "metering-bucket": 7 // default metering bucket that will be used in case mapping has metering bucket set to 0
                    },
                    ]
```
why not have both prefixes in one single route object since everything else is same ?
```
                "routes": [
                    {
                        "ip-prefixes": [ "10.1.0.0/16",
                                               "10.1.0.128/28" ],
                        "action" : {
                            "routing-type": "vpc", // vnet route - destination within vnet, needs mapping table lookup
                            "vpc-id": "559c6ce8-26ab-4193-b946-ccc6e8f930b2"
                        },
                        "metering-bucket": 7 // default metering bucket that will be used in case mapping has metering bucket set to 0
                    },

                    ]
```
are both configs valid and is just a matter of preference ?

**Comment by chrispsommers** [comment]
Hi @KrisNey-MSFT Can you assign this to the right person in SDN team? Thanks!

**Comment by prsunny** [comment]
This was done intentionally to keep it aligned with Sonic schema. IP prefix is used as the key for the Route and hence not it is not conveyed as "list"

**Comment by prsunny** [comment]
Please reopen if you've further questions.

**Comment by mgheorghe** [comment]
but it looks like a list with one element, implying we could add more
"ip-prefixes": [ "10.1.0.0/16" ]
if we do not desire a list maybe we can keep it as a string
"ip-prefixes": "10.1.0.0/16"


not having it as a list will increase the "file" size by a lot since for every route we have to repeat 7 lines  (large amount of repeating data/characters, for every route,  up to 1M - 10M (dash scale)
                    {
                        "action" : {
                            "routing-type": "vpc", // vnet route - destination within vnet, needs mapping table lookup
                            "vpc-id": "559c6ce8-26ab-4193-b946-ccc6e8f930b2"
                        },
                        "metering-bucket": 7 // default metering bucket that will be used in case mapping has metering bucket set to 0
                    },

**Comment by prsunny** [comment]
Which file size? The example reference file is not the one used for actual configuration.

**Comment by mgheorghe** [comment]
can we have the one used for actual config ?
