### ISSUE TITLE
make run-all-tests (in dash-pipeline) fails

### ISSUE THREAD

**Issue by mhanif** [Azure/DASH#186]
make run-all-tests (in dash-pipeline) fails with the following error.  I cloned a fresh version and followed the instructions.  Essentially running (successfully) make all && make run-switch in one window and make run-saithrift-server in another window.  When attempting to run make run-all-tests in another window, I get the following error.  I have not modified any code - only followed the instructions in the readme.

GRPC call SetForwardingPipelineConfig 0.0.0.0:9559 => /etc/dash/dash_pipeline.json, /etc/dash/dash_pipeline_p4rt.txt
GRPC ERROR[7]: Not primary, GRPC call Write::INSERT ERROR:
table_id: 41103078 match { field_id: 1 exact { value: "<\000\000" } } action { action { action_id: 21912829 } }Failed to create Direction Lookup Entry
make: *** [Makefile:253: run-libsai-test] Error 1

**Comment by mhanif** [comment]
Update: I re-ran the make command and it succeeded.

**Comment by chrispsommers** [comment]
Hi @mhanif I suspect you have more than one instance of a P4Runtime client running. This is the clue:
```
GRPC ERROR[7]: Not primary
```
Please perform "docker ps" and see if there's another client running.

**Comment by chrispsommers** [comment]
@mhanif Can we close this? It seems like a transient. With the many recent improvements to the build process, there's a good chance the environment is sufficiently different such as to make this issue somewhat stale. Thanks.

**Comment by mhanif** [comment]
@chrispsommers Yes, we can close this.  Thanks a lot for helping improve the build process.  I will close this issue.
