### ISSUE TITLE
Is there any way to participate in DASH project？

### ISSUE THREAD

**Issue by hubblezzhu** [Azure/DASH#200]
Hi everyone, I am very interested in DASH and want to know more about DASH P4 Behavior model. 

Is there any way to participate in this DASH project？
![image](https://user-images.githubusercontent.com/14011375/185023632-47b00ae6-806b-4d06-9fb2-5964a63f3080.png)

any help will be appreciated. :)

**Comment by mgheorghe** [comment]
hi hubblezzhu please join https://groups.google.com/g/sonic-dash and also the Wednesday community meeting

**Comment by hubblezzhu** [comment]
> hi hubblezzhu please join https://groups.google.com/g/sonic-dash and also the Wednesday community meeting

OK, I have joined the groups,  looking forward to the next community meeting.

**Comment by KrisNey-MSFT** [comment]
Hello @hubblezzhu - invite sent!
Thank you, Kristina

**Comment by hubblezzhu** [comment]
> Hello @hubblezzhu - invite sent! Thank you, Kristina

thanks very much!

**Comment by hubblezzhu** [comment]
hi @KrisNey-MSFT , by the way, is there a weblink to the next weekly meeting on Wednesday?

**Comment by KrisNey-MSFT** [comment]
hi @hubblezzhu , it is a Teams call, the link is in the invite.  If you don't have Teams installed, I believe it will try to open via a browser.
