### ISSUE TITLE
Does DASH require VM appliance encapsulate VXLAN?

### ISSUE THREAD

**Issue by zhi42** [Azure/DASH#214]
![image](https://user-images.githubusercontent.com/112915613/188535054-4800b811-abf2-42a7-862c-1fd47dc1dbb3.png)
**•	The incoming packet will always be VXLAN encapsulated and the outer dst-ip is the appliance VIP.**
Based on the description on Vnet2Vnet scenario, it looks like the outbound (vm to Ethernet) packet already has VXLAN encapsulated when send out from VM? Does it mean DASH require VM appliance encapsulate VXLAN? If so , how does VM appliance get VXLAN encapsulation rule? Thanks.

**Comment by mhanif** [comment]
@zhi42 I am not sure if this question belongs in the issues section.  In any case, I will try to answer it.  From VM appliance, I believe you mean a server which is hosting a set of VMs.  It is expected that a server has a sub-system (e.g. a NIC) which will encapsulate an outbound packet into a VxLAN tunnel.  A server will get VxLAN encapsulation rules based on certain configurations.

**Comment by zhi42** [comment]
Hi Mohammad

Thanks for you kindly reply, my original idea is that DASH may provide new method to implement tunnel encap/decap (Vxlan,GRE,..etc.) on NIC through SONiC/SAI.
Based on your elaboration this is not the target of DASH, now I understood.
Thanks again.


发件人: Mohammad Hanif ***@***.***>
发送时间: 2022年9月12日 7:14
收件人: Azure/DASH ***@***.***>
抄送: Zhi Luo ***@***.***>; Mention ***@***.***>
主题: Re: [Azure/DASH] Does DASH require VM appliance encapsulate VXLAN? (Issue #214)


@zhi42<https://github.com/zhi42> I am not sure if this question belongs in the issues section. In any case, I will try to answer it. From VM appliance, I believe you mean a server which is hosting a set of VMs. It is expected that a server has a sub-system (e.g. a NIC) which will encapsulate an outbound packet into a VxLAN tunnel. A server will get VxLAN encapsulation rules based on certain configurations.
