### ISSUE TITLE
Incomplete ACL rule libsai implementation for bmv2 P4 pipeline

### ISSUE THREAD

**Issue by mukeshmv** [Azure/DASH#232]
P4 code for dash pipeline on bmv2 has multiple instances of ACL tables (1 per stage per direction). 
Whereas SAI has a single API for creating ACL rules that could belong to any stage. 
Current auto-gen libsai code only populates one of these P4 ACL tables irrespective of where the ACL rule belongs. 
This needs to be fixed.

**Comment by KrisNey-MSFT** [comment]
Cover in bmv2 meeting

**Comment by KrisNey-MSFT** [comment]
Engineer is working w/ @marian-pritsak to solve.

**Comment by yusefMS06** [comment]
@mukeshmv Any big updates on this issue, wanted to add a tag to the progress session.

**Comment by chrispsommers** [comment]
This PR https://github.com/Azure/DASH/pull/265 seems to be related.

**Comment by Pterosaur** [comment]
As Chris said, the PR https://github.com/Azure/DASH/pull/265 is for fixing this issue.

**Comment by yusefMS06** [comment]
Marking as closed
