### ISSUE TITLE
Mention of Azure in Glossary

### ISSUE THREAD

**Issue by GeraldatMicrosoft** [Azure/DASH#39]
I noticed in the Overlay definition (in the glossary) there was a reference to Azure customers when discussing the APIs. DASH is not owned by Microsoft or Azure and will remain a public and open source of information. We should remove all references to Azure and use other words in it’s place like customer SDN, SDN orchestrator and such. 

DASH will be used in the enterprise and other clouds who will orchestrate the services that fit their own individual needs. Over time we all hope that DASH will provide high level guidance to the lower level implementations of smart devices to get the most out of them without overly complicating scenarios with infinite flexibility leading to sub-optimal performance.

**Comment by KrisNey-MSFT** [comment]
Glossary reviewed, references specifically to 'Azure' removed.
Closing issue.
