### ISSUE TITLE
Application table in P4 pipeline code

### ISSUE THREAD

**Issue by budgrise** [Azure/DASH#76]
Not sure if this is the best place to ask these questions, but here goes.
(This is primarily addressed to Marian) 

In the sirius_pipeline.p4 code, "table appliance" is defined.
The table's key is an appliance_id. Do we expect that there are multiple 
appliance entries, and if so where does the index come from? Or is
this table really just a single entry with some global attributes?

One of the attributes is "neighbor_mac", and is used for the outer dmac 
when encapping the vxlan header stack onto the packet. I wanted to 
double-check that there is indeed one such mac address (and that putting
the attribute here was not just a placeholder).

Thanks,
Bud

**Comment by KrisNey-MSFT** [comment]
This is the global attributes of the appliance (catch-all entry).  Look at SAI API, this is mapped to underlay attributes.  Based on the table, no new table is generated, it will be translated into SAI attributes.  
Neighbor-mac is the ToR switch's MAC connected to the Appliance.
