### ISSUE TITLE
XN: In Compiler

### ISSUE THREAD

**Issue by KrisNey-MSFT** [Azure/DASH#82]
## Related Information 

Owner - Nvidia. Scope - p4c. Requires support for new table properties such as add_on_miss, idle_timeout_with_auto_delete, default_action.

### Issues
- [Connection Tracking: Too loose, UDP and Aging](https://github.com/Azure/DASH/issues/10)

### Pull requests
- [PNA compatible connection tracking #21](https://github.com/Azure/DASH/pull/21)

**Comment by KrisNey-MSFT** [comment]
Early Sept (Roop finished, need to merge & build compiler from fork)

**Comment by KrisNey-MSFT** [comment]
Keep these separate

**Comment by yusefMS06** [comment]
@marian-pritsak Issue marked as shipped, can we close issue?

**Comment by yusefMS06** [comment]
@chrispsommers can we mark as closed?

**Comment by yusefMS06** [comment]
Discussed with WG. Moving to closed
