### ISSUE TITLE
IPv6 routing support

### ISSUE THREAD

**Issue by KrisNey-MSFT** [Azure/DASH#88]
## Related information
Scope - P4 DASH pipeline. Requires definition of IPv6 header in overlay pipeline headers, proper parsing, and match on L3 addresses along with IPv4 addresses.

@marian-pritsak to provide further information, give to Hanif.

### Notes
Needs to be coded in P4 behavioral model
No change in bmv2, just P4

**Comment by mhanif** [comment]
Hi @marian-pritsak, Not sure if you saw my email.  As discussed, please send me the information on an equivalent IPv4 model.  Also, please share the development and testing environment details as well.  Thanks!

**Comment by KrisNey-MSFT** [comment]
Adding Marian's email...

425-876-2040 cell
________________________________

**Comment by marian-pritsak** [comment]
Hi Mohammad,

The following list of tables will require IPv6 support:
* sirius_outbound.routing
* sirius_outbound.ca_to_pa
* ACL stages (sirius_acl file)

all those tables match on IPv4 address. We need to support matching on either IPv4 address or IPv6 address depending on the packet's overlay ethertype.

**Comment by mariobaldi** [comment]
We will need IPv6 support also in connection tracking, hence generally throughout sirius_conntrack.p4.

 

My suggestion would be to first finalize connection tracking with the proper connection removal behavior just for IPv4 (building on the current version of the code) and then later add IPv6 support.
