### ISSUE TITLE
Support for list-match type (P4) for ACLs, pending BMV2 fork

### ISSUE THREAD

**Issue by KrisNey-MSFT** [Azure/DASH#91]
## Related information
Scope - BMv2. DASH ACL defines two new match types - list and range_list. They need to be handled by the simulator, so it can match a field in a packet against a list of values and generate a hit if one of the values in the list matches.

**Comment by mqasimfarooqi** [comment]
Hi @marian-pritsak,

I was working on adding the "list" match type in the simulator.

I needed some clarification on how this match type actually works. In the task description it is written that it will match with a list of values, so what type of match will it be? Is it equivalent to adding multiple entries of same data type in the table? Or will it be a list of multiple data types e.g mac, ip etc?

I have identified 3 areas of development, please correct if I'm wrong:
1. json parsing for "list".
2. Runtime handling.
3. Datapath implementation for "list".
I believe support needs to be added in these 3 areas, am I correct?

Also it would be great if you could share some reference material (e.g any past discussion) to gain further understanding on this.

Best Regards,
Qasim

**Comment by mqasimfarooqi** [comment]
It seems that support for list-match type also needs to be added in the p4c. We have observed that the table match_type does not update to list in the generated json file. For now we have manually changed the match_type to list in json file to continue development.

Is there any past discussion on how the table match_type is decided if a table contains mix types with list and range_list in them?

We have assumed that for an ipv4 key it would look something like this "192.168.10.0/24,192.168.9.0/24" etc. For other key values like protocol an entry would look like "value1&&&mask1,value2&&&mask2".

**Comment by KrisNey-MSFT** [comment]
@marian-pritsak to reply 4/21/2022

**Comment by marian-pritsak** [comment]
Hi @mqasimfarooqi 

Datapath and runtime for sure, however, what section in JSON are you talking about that is not updated?

**Comment by mqasimfarooqi** [comment]
Hi @marian-pritsak 

p4c generates table_match_type by parsing key match_types using the following rules:

// Decreasing order of precedence (bmv2 specification):
                // 0) more than one LPM field is an error
                // 1) if there is at least one RANGE field, then the table is RANGE
                // 2) if there is at least one TERNARY or OPTIONAL field, then the table is TERNARY
                // 3) if there is a LPM field, then the table is LPM
                // 4) otherwise the table is EXACT

We have seen that when we have only "list" match-types for keys it does not change table type to "list".
![Table Match Type](https://user-images.githubusercontent.com/102615584/164571640-e3331464-93de-407b-b5fa-1c1a85a47d55.jpg)

**Comment by marian-pritsak** [comment]
Yes, this field needs to be also updated to "list".

List and range_list should be in positions 1 and 2 (before LPM and ternary).

**Comment by mqasimfarooqi** [comment]
@KrisNey-MSFT, I believe p4c is out of scope of this issue. Will there be separate issue for this or an extension to the current issue?

**Comment by KrisNey-MSFT** [comment]
I'll let @Marian ***@***.***> respond...

**Comment by KrisNey-MSFT** [comment]
P4C defines the match-type of the table.  The compiler code needs to be updated (?); this is out of scope b/c this is only bmv2.  
@marian-pritsak is not sure if this affects anything.   
Changed the table match type (.json file) to list, to continue dev process.  
Based on the key values, it changes the table-match-type.  List is not yet implemented in the compiler.  Why does bmv2 need to know the table match type, what is it being used for?  Being used to make decisions in the code.  
We have no preference whether this is a new Issue or continues in this one.
Some development left on the range-list, and open PR in the coming week in Qasim's fork.

**Comment by KrisNey-MSFT** [comment]
Per @mqasimfarooqi - let's move forward and extend the scope of to encompass p4c and bmv2.

I think, in the first comment, we may change "Scope - BMv2" to "Scope - BMv2,p4c" and add a line in the end to define the other related task which should be "In the compiler, handle list and range_list key values to decide table match type based on precedence.". Rest looks okay.

**Comment by mqasimfarooqi** [comment]
https://github.com/marian-pritsak/behavioral-model/pull/1

**Comment by mqasimfarooqi** [comment]
https://github.com/marian-pritsak/behavioral-model/pull/1

**Comment by KrisNey-MSFT** [comment]
Hi @mqasimfarooqi  - Marian has a few updated PRs, one in /opencomputeproject, one in /DASH.  Do either of these affect your Issue here?

https://github.com/Azure/DASH/pull/249 - Build p4c from custom fork
https://github.com/opencomputeproject/SAI/pull/1630 - Change ACL address key to prefix list

**Comment by yusefMS06** [comment]
@mqasimfarooqi Were the PRs mentioned above helpful in solving your issue? Been some time since this was reviewed, can we move to close?

**Comment by mqasimfarooqi** [comment]
Hi @KrisNey-MSFT  @yusefMS06 - Sorry for the delayed response.

@KrisNey-MSFT  - Actually the feature is already merged with Marian's bmv2 fork. I don't think the above mentioned PR's should effect this issue. We can close this issue.

@yusefMS06 - Yes please, we can go ahead and close this issue as the change-set has been merged in Marian's bmv2 fork.

**Comment by yusefMS06** [comment]
Going ahead and closing
